# Generated by Django 5.2.12 on 2026-04-04 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.URLField(default='placeholder.svg')),
                ('technologies', models.CharField(help_text='Technologies separated by commas', max_length=500)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('analysis', 'Analyse de données'), ('programming', 'Programmation'), ('database', 'Bases de données'), ('bi', 'Business Intelligence')], max_length=20)),
                ('icon', models.CharField(default='fas fa-chart-line', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_company', models.CharField(blank=True, max_length=100)),
                ('client_image', models.URLField(default='placeholder.svg')),
                ('message', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='DELAMOU Samaké', max_length=100)),
                ('title', models.CharField(default='Data Analyst', max_length=100)),
                ('bio', models.TextField(default="Passionné par l'analyse de données et l'extraction d'insights pertinents pour aider les entreprises à prendre des décisions éclairées.")),
                ('profile_image', models.URLField(default='delamou.jpg')),
                ('email', models.EmailField(default='delamou.samake@email.com', max_length=254)),
                ('phone', models.CharField(default='+223 XX XX XX XX', max_length=20)),
                ('location', models.CharField(default='Conakry, Guinée', max_length=100)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('kaggle', models.URLField(blank=True, null=True)),
                ('years_experience', models.PositiveIntegerField(default=3)),
                ('projects_count', models.PositiveIntegerField(default=50)),
                ('clients_count', models.PositiveIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
