# Generated by Django 5.2.12 on 2026-04-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_visible',
            field=models.BooleanField(default=True, help_text="Détermine si le projet est affiché sur la page d'accueil"),
        ),
    ]
